# Generated by Django 5.1.7 on 2025-03-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='date_maintained',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='owner_number',
            field=models.IntegerField(null=True),
        ),
    ]
